//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErlezQue.BullDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public int Id { get; set; }
        public string ArticleName { get; set; }
        public System.Guid Gtin { get; set; }
        public Nullable<int> CompanySellerId { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public string UnitType { get; set; }
    
        public virtual CompanySeller CompanySeller { get; set; }
    }
}
