//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErlezQue.BullDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public Invoice()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int Id { get; set; }
        public Nullable<int> InvoiceNo { get; set; }
        public string SellerName { get; set; }
        public string SellerOrgNo { get; set; }
        public string SellerCity { get; set; }
        public string BuyerName { get; set; }
        public string BuyerOrgNo { get; set; }
        public string BuyerCity { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> TotalNet { get; set; }
        public Nullable<decimal> TotalTax { get; set; }
        public Nullable<decimal> TotalSum { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
    }
}
