//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErlezQue.BullDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public Nullable<int> InvoiceId { get; set; }
        public string OrderType { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<int> CompanySellerId { get; set; }
        public Nullable<int> CompanyBuyerId { get; set; }
        public decimal Amount { get; set; }
        public Nullable<System.Guid> Gtin { get; set; }
        public string ArticleName { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public string UnitType { get; set; }
    
        public virtual CompanyBuyer CompanyBuyer { get; set; }
        public virtual CompanySeller CompanySeller { get; set; }
        public virtual Invoice Invoice { get; set; }
    }
}
