//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErlezQue.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bet
    {
        public int PostId { get; set; }
        public string DueDate { get; set; }
        public string DueDays { get; set; }
        public string InvCurrency { get; set; }
        public string TaxCurrency { get; set; }
        public string TaxCurrencyRate { get; set; }
        public string TaxCurrencyRateDate { get; set; }
        public string ExemptFromTax { get; set; }
        public string PenaltySurchargePercent { get; set; }
        public string PaymentInstruction { get; set; }
    
        public virtual Head Head { get; set; }
    }
}
