//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErlezQue.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int PostId { get; set; }
        public int CompanyCount { get; set; }
        public string CompanyQual { get; set; }
        public string PartyIdentification { get; set; }
        public string VatNo { get; set; }
        public string OrgNo { get; set; }
        public string CustomerNumber { get; set; }
        public string SellerUniqueIdentification { get; set; }
        public string Name { get; set; }
        public string ContactName { get; set; }
        public string ContactTel { get; set; }
        public string ContactEmail { get; set; }
        public string ContactFax { get; set; }
        public string StreetName { get; set; }
        public string AdditionalStreetName { get; set; }
        public string ZipCode { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string Box { get; set; }
        public string Department { get; set; }
        public string BankCode { get; set; }
        public string BankName { get; set; }
        public string BankAccount { get; set; }
        public string Iban { get; set; }
        public string PlusGiro { get; set; }
        public string BankGiro { get; set; }
        public Nullable<int> Head_PostId { get; set; }
    
        public virtual Head Head { get; set; }
    }
}
