//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErlezQue.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanySeller
    {
        public CompanySeller()
        {
            this.Articles = new HashSet<Article>();
            this.Orders = new HashSet<Order>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string OrgNo { get; set; }
        public string City { get; set; }
    
        public virtual ICollection<Article> Articles { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}
