//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErlezQue.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class HeadRef
    {
        public int PostId { get; set; }
        public int HeadRefCount { get; set; }
        public string HeadRefQual { get; set; }
        public string HeadRef1 { get; set; }
        public string HeadRefDate { get; set; }
        public Nullable<int> Head_PostId { get; set; }
    
        public virtual Head Head { get; set; }
    }
}
