//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErlezQue.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Head
    {
        public Head()
        {
            this.Alcs = new HashSet<Alc>();
            this.Companies = new HashSet<Company>();
            this.Enclosures = new HashSet<Enclosure>();
            this.HeadRefs = new HashSet<HeadRef>();
            this.Lines = new HashSet<Line>();
            this.SumTaxes = new HashSet<SumTax>();
            this.Tdts = new HashSet<Tdt>();
            this.Tods = new HashSet<Tod>();
        }
    
        public int PostId { get; set; }
        public string IAID { get; set; }
        public string Flow { get; set; }
        public string InvoiceNo { get; set; }
        public string OutputType { get; set; }
        public Nullable<int> UpdateCode { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string InvoiceType { get; set; }
        public string InvoiceDate { get; set; }
        public string RealDelDate { get; set; }
        public string RealDelShip { get; set; }
        public string HorizonStartDate { get; set; }
        public string HorizonEndDate { get; set; }
        public string PeriodFrom { get; set; }
        public string PeriodTo { get; set; }
        public string CreditReason { get; set; }
        public string MaterialType { get; set; }
        public string GUID { get; set; }
        public string Timestamp { get; set; }
        public string ErpVersion { get; set; }
        public string isTest { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public string CorporateGroup { get; set; }
        public string Erp { get; set; }
        public string Version { get; set; }
        public Nullable<int> FromID { get; set; }
        public string Hash { get; set; }
    
        public virtual ICollection<Alc> Alcs { get; set; }
        public virtual Bet Bet { get; set; }
        public virtual ICollection<Company> Companies { get; set; }
        public virtual ICollection<Enclosure> Enclosures { get; set; }
        public virtual ICollection<HeadRef> HeadRefs { get; set; }
        public virtual ICollection<Line> Lines { get; set; }
        public virtual Sum Sum { get; set; }
        public virtual ICollection<SumTax> SumTaxes { get; set; }
        public virtual ICollection<Tdt> Tdts { get; set; }
        public virtual ICollection<Tod> Tods { get; set; }
    }
}
