//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErlezQue.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Line
    {
        public Line()
        {
            this.LineAlcs = new HashSet<LineAlc>();
            this.LinePris = new HashSet<LinePri>();
            this.LineRefs = new HashSet<LineRef>();
            this.LineTaxes = new HashSet<LineTax>();
        }
    
        public int PostId { get; set; }
        public long LineId { get; set; }
        public int LineCount { get; set; }
        public string LineNumber { get; set; }
        public string GtinNo { get; set; }
        public string SellerPartNo { get; set; }
        public string BuyerPartNo { get; set; }
        public string ManufPartNo { get; set; }
        public string QuantityInvoiced { get; set; }
        public string QuantityInvoicedUnit { get; set; }
        public string QuantityDelivered { get; set; }
        public string QuantityDeliveredUnit { get; set; }
        public string QuantityDespatched { get; set; }
        public string QuantityDespatchedUnit { get; set; }
        public string QuantityReceived { get; set; }
        public string QuantityReceivedUnit { get; set; }
        public string LineAmount { get; set; }
        public string Description { get; set; }
        public string Description2 { get; set; }
        public string CreditReason { get; set; }
        public string Revision { get; set; }
        public string Origin { get; set; }
        public string DelDate { get; set; }
        public string FirstDelDate { get; set; }
        public string LastDelDate { get; set; }
        public string LineType { get; set; }
        public Nullable<int> Head_PostId { get; set; }
    
        public virtual Head Head { get; set; }
        public virtual ICollection<LineAlc> LineAlcs { get; set; }
        public virtual ICollection<LinePri> LinePris { get; set; }
        public virtual ICollection<LineRef> LineRefs { get; set; }
        public virtual ICollection<LineTax> LineTaxes { get; set; }
    }
}
