//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErlezQue.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ErlezWebUIEntities : DbContext
    {
        public ErlezWebUIEntities()
            : base("name=ErlezWebUIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Alc> Alcs { get; set; }
        public virtual DbSet<Article> Articles { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Bet> Bets { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<CompanyB2> CompanyB2 { get; set; }
        public virtual DbSet<CompanyBuyer> CompanyBuyers { get; set; }
        public virtual DbSet<CompanySeller> CompanySellers { get; set; }
        public virtual DbSet<Enclosure> Enclosures { get; set; }
        public virtual DbSet<Head> Heads { get; set; }
        public virtual DbSet<HeadRef> HeadRefs { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<Line> Lines { get; set; }
        public virtual DbSet<LineAlc> LineAlcs { get; set; }
        public virtual DbSet<LinePri> LinePris { get; set; }
        public virtual DbSet<LineRef> LineRefs { get; set; }
        public virtual DbSet<LineTax> LineTaxes { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Sum> Sums { get; set; }
        public virtual DbSet<SumTax> SumTaxes { get; set; }
        public virtual DbSet<Tdt> Tdts { get; set; }
        public virtual DbSet<Tod> Tods { get; set; }
    }
}
