//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErlezQue.BillDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alc
    {
        public int PostId { get; set; }
        public int AlcCount { get; set; }
        public string AlcType { get; set; }
        public string Type { get; set; }
        public string Percentage { get; set; }
        public string BaseAmount { get; set; }
        public string Amount { get; set; }
        public string TaxType { get; set; }
        public string TaxCategory { get; set; }
        public string TaxRate { get; set; }
        public string TaxAmount { get; set; }
    
        public virtual Head Head { get; set; }
    }
}
