//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErlezQue.BillDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enclosure
    {
        public int PostId { get; set; }
        public int EnclosureCount { get; set; }
        public string MediaType { get; set; }
        public string FileName { get; set; }
        public string FileCreationDate { get; set; }
        public string EnclosedDataFormat { get; set; }
        public string EnclosedData { get; set; }
    
        public virtual Head Head { get; set; }
    }
}
