//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErlezQue.BillDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class LinePri
    {
        public long LineId { get; set; }
        public int LinePriCount { get; set; }
        public string PriceQualifier { get; set; }
        public string PriceType { get; set; }
        public string PriceTypeQualifier { get; set; }
        public string LinePri1 { get; set; }
        public string LinePriBase { get; set; }
        public string LineUnit { get; set; }
    
        public virtual Line Line { get; set; }
    }
}
