//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErlezQue.BillDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class LineTax
    {
        public long LineId { get; set; }
        public int LineTaxCount { get; set; }
        public string LineTaxType { get; set; }
        public string LineTaxCategory { get; set; }
        public string LineTaxRate { get; set; }
        public string LineTaxAmount { get; set; }
        public string ExemptFromTax { get; set; }
    
        public virtual Line Line { get; set; }
    }
}
