//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErlezQue.BillDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class SumTax
    {
        public int PostId { get; set; }
        public int SumTaxCount { get; set; }
        public string SumTaxType { get; set; }
        public string SumTaxCategory { get; set; }
        public string SumTaxRate { get; set; }
        public string SumTaxableAmount { get; set; }
        public string SumTaxAmount { get; set; }
        public string TaxCurrencyTaxAmount { get; set; }
    
        public virtual Head Head { get; set; }
    }
}
