//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErlezQue.BillDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tdt
    {
        public int PostId { get; set; }
        public int TdtCount { get; set; }
        public string TdtMethod { get; set; }
        public string TdtDescription { get; set; }
        public string TdtCarrierName { get; set; }
    
        public virtual Head Head { get; set; }
    }
}
