//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErlezQue.BillDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tod
    {
        public int PostId { get; set; }
        public int TodCount { get; set; }
        public string TodTerms { get; set; }
        public string TodDescription { get; set; }
        public string TodTermsLoc { get; set; }
    
        public virtual Head Head { get; set; }
    }
}
